name: Build & Deploy Hugo Blog

on:
  push:
    branches: 
      - master
    paths:
      - public_html/blog

jobs:
  build:
    name: Build and Deploy on Linode
    runs-on: ubuntu-latest
    steps:
    - name: Run Hugo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true # stop the script immediately if any commands fail
        script: |
          cd ${{ secrets.HUGO_DIR }}
          hugo

